// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx5beFmXMkyXA55TpE2-vRYqjD48OZIck',
    appId: '1:518390056031:web:7ca51b70e73947426b47ea',
    messagingSenderId: '518390056031',
    projectId: 'redditclone-d84ad',
    authDomain: 'redditclone-d84ad.firebaseapp.com',
    storageBucket: 'redditclone-d84ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMGuy8CIoUXL_xleTHor-V6APs_gbwocQ',
    appId: '1:518390056031:android:6422190250150f2f6b47ea',
    messagingSenderId: '518390056031',
    projectId: 'redditclone-d84ad',
    storageBucket: 'redditclone-d84ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxu5llF8JHQKUBO4xOG-9nulKkCJIMuqw',
    appId: '1:518390056031:ios:8ee080abc25736ee6b47ea',
    messagingSenderId: '518390056031',
    projectId: 'redditclone-d84ad',
    storageBucket: 'redditclone-d84ad.appspot.com',
    iosBundleId: 'com.clone.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxu5llF8JHQKUBO4xOG-9nulKkCJIMuqw',
    appId: '1:518390056031:ios:4c71bb163df86c476b47ea',
    messagingSenderId: '518390056031',
    projectId: 'redditclone-d84ad',
    storageBucket: 'redditclone-d84ad.appspot.com',
    iosBundleId: 'com.clone.reddit.RunnerTests',
  );
}
